# Лабораторная работа по курсу "Искусственный интеллект"
# Многослойный персептрон

|Студент | Егорова А. В. |
|---------|--------|
|Группа | М8О-307Б-18  |



## Подготовка данных

In [1]:
import numpy as np
import tensorflow as tf

TRAIN_COUNT = 60000
TEST_COUNT = 10000

Подготовка датасетов MNIST и FashionMNIST.

In [2]:
(x_train1, y_train1), (x_test1, y_test1) = tf.keras.datasets.mnist.load_data()
(x_train2, y_train2), (x_test2, y_test2) = tf.keras.datasets.fashion_mnist.load_data()

In [3]:
x_train1, x_test1 = x_train1.reshape(TRAIN_COUNT, 784).astype('float32') / 255.0, x_test1.reshape(TEST_COUNT, 784).astype('float32') / 255.0
x_train2, x_test2 = x_train2.reshape(TRAIN_COUNT, 784).astype('float32') / 255.0, x_test2.reshape(TEST_COUNT, 784).astype('float32') / 255.0

Разделение выборки на тренировочную и тестирующую.

In [4]:
# MNIST
dataset1 = tf.data.Dataset.from_tensor_slices((x_train1, y_train1))
dataset1 = dataset1.shuffle(buffer_size=1024).batch(64)

# FashionMNIST
dataset2 = tf.data.Dataset.from_tensor_slices((x_train2, y_train2))
dataset2 = dataset2.shuffle(buffer_size=1024).batch(64)

## Обучение

In [5]:
def training(dataset, cur_x_test, cur_y_test, loss, accuracy, optimizer):
   
    # 1 layer
    
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(10)
    ])
    model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
    h = model.fit(dataset, epochs=3, batch_size=None, verbose=0)
    score = model.evaluate(cur_x_test, cur_y_test, verbose=0)

    print("Layers: 1")
    print("Testing loss:", score[0])
    print("Testing accuracy:", score[1])
    print("Loss:", h.history['loss'][-1])
    print("Accuracy:", h.history['sparse_categorical_accuracy'][-1], '\n')

    # 2 layers, tahn

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation=tf.nn.tanh),
        tf.keras.layers.Dense(10)
    ])
    model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
    h = model.fit(dataset, epochs=3, batch_size=None, verbose=0)
    score = model.evaluate(cur_x_test, cur_y_test, verbose=0)


    print("Layers: 2, func: tanh")
    print("Testing loss:", score[0])
    print("Testing accuracy:", score[1])
    print("Loss:", h.history['loss'][-1])
    print("Accuracy:", h.history['sparse_categorical_accuracy'][-1], '\n')

    # 2 layers, sigmoid

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation=tf.nn.sigmoid),
        tf.keras.layers.Dense(10)
    ])
    model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
    h = model.fit(dataset, epochs=3, batch_size=None, verbose=0)
    score = model.evaluate(cur_x_test, cur_y_test, verbose=0)

    print("Layers: 2, func: sigmoid")
    print("Testing loss:", score[0])
    print("Testing accuracy:", score[1])
    print("Loss:", h.history['loss'][-1])
    print("Accuracy:", h.history['sparse_categorical_accuracy'][-1], '\n')

    # 3 layers, tahn & sigmoid

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation=tf.nn.tanh),
        tf.keras.layers.Dense(512, activation=tf.nn.sigmoid),
        tf.keras.layers.Dense(10)
    ])
    model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
    h = model.fit(dataset, epochs=3, batch_size=None, verbose=0)
    score = model.evaluate(cur_x_test, cur_y_test, verbose=0)

    print("3 layers with tanh & sigmoid")
    print("Testing loss:", score[0])
    print("Testing accuracy:", score[1])
    print("Loss:", h.history['loss'][-1])
    print("Accuracy:", h.history['sparse_categorical_accuracy'][-1], '\n')
    
    
    # 3 layers, 2 sigmoid

    model = tf.keras.Sequential([
        tf.keras.layers.Dense(256, activation=tf.nn.sigmoid),
        tf.keras.layers.Dense(512, activation=tf.nn.sigmoid),
        tf.keras.layers.Dense(10)
    ])
    model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
    h = model.fit(dataset, epochs=3, batch_size=None, verbose=0)
    score = model.evaluate(cur_x_test, cur_y_test, verbose=0)

    print("3 layers with sigmoid & sigmoid")
    print("Testing loss:", score[0])
    print("Testing accuracy:", score[1])
    print("Loss:", h.history['loss'][-1])
    print("Accuracy:", h.history['sparse_categorical_accuracy'][-1], '\n')


MNIST:

In [6]:
training(
    dataset = dataset1,
    cur_x_test = x_test1,
    cur_y_test = y_test1,
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    accuracy = tf.keras.metrics.SparseCategoricalAccuracy(),
    optimizer = tf.keras.optimizers.Adam())


1 layer
Loss: 0.29682064056396484
Accuracy: 0.9171666502952576
Testing loss: 0.2831864356994629
Testing accuracy: 0.9203000068664551

2 layers with tanh
Loss: 0.07422779500484467
Accuracy: 0.9781833291053772
Testing loss: 0.08824454247951508
Testing accuracy: 0.9710999727249146

2 layers with sigmoid
Loss: 0.12220337986946106
Accuracy: 0.9643499851226807
Testing loss: 0.11839892715215683
Testing accuracy: 0.964900016784668

3 layers with tanh & sigmoid
Loss: 0.061952199786901474
Accuracy: 0.9812833070755005
Testing loss: 0.08688589930534363
Testing accuracy: 0.9732000231742859

3 layers with sigmoid & sigmoid
Loss: 0.08046679198741913
Accuracy: 0.9756333231925964
Testing loss: 0.08865723013877869
Testing accuracy: 0.9718999862670898



Fashion MNIST:

In [7]:
training(
    dataset = dataset2,
    cur_x_test = x_test2,
    cur_y_test = y_test2,
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    accuracy = tf.keras.metrics.SparseCategoricalAccuracy(),
    optimizer = tf.keras.optimizers.Adam())


1 layer
Loss: 0.4498845040798187
Accuracy: 0.8461499810218811
Testing loss: 0.46982303261756897
Testing accuracy: 0.8377000093460083

2 layers with tanh
Loss: 0.3211295008659363
Accuracy: 0.8818666934967041
Testing loss: 0.35889381170272827
Testing accuracy: 0.8698999881744385

2 layers with sigmoid
Loss: 0.3372385501861572
Accuracy: 0.878083348274231
Testing loss: 0.37622344493865967
Testing accuracy: 0.8655999898910522

3 layers with tanh & sigmoid
Loss: 0.3161698281764984
Accuracy: 0.8827666640281677
Testing loss: 0.3530091941356659
Testing accuracy: 0.8723000288009644

3 layers with sigmoid & sigmoid
Loss: 0.3211168348789215
Accuracy: 0.8819166421890259
Testing loss: 0.3716796636581421
Testing accuracy: 0.8622000217437744



Наибольшая точность достигается в последнем случае.

## Сравнение полученных показателей точности модели для различных гиперпараметров

В качестве гиперпараметра берем ширину внутренних слоёв.

In [8]:
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
accuracy = tf.keras.metrics.SparseCategoricalAccuracy()
optimizer = tf.keras.optimizers.Adam()
dataset = dataset2
epochs = 3
cur_x_test = x_test2
cur_y_test = y_test2

test_h1 = 256
test_w1 = 256

model = tf.keras.Sequential([
    tf.keras.layers.Dense(test_h1, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(test_w1, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(10)
])

model.compile(loss=loss,
              metrics=[accuracy],
              optimizer=tf.keras.optimizers.Adam())
h1 = model.fit(dataset, epochs=epochs, batch_size=None, verbose=0)
score = model.evaluate(cur_x_test, cur_y_test, verbose=0)
pred1 = np.argmax(model.predict(cur_x_test, verbose=0), axis=1)

print(f"3 layers with sigmoid & sigmoid ({test_h1}х{test_w1})")
print("Testing loss:", score[0])
print("Testing accuracy:", score[1])
print("Loss:", h1.history['loss'][-1])
print("Accuracy:", h1.history['sparse_categorical_accuracy'][-1], '\n')

test_h2 = 512
test_w2 = 256

model = tf.keras.Sequential([
    tf.keras.layers.Dense(test_h2, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(test_w2, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(10)
])
model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
h2 = model.fit(dataset, epochs=epochs, batch_size=None, verbose=0)
score = model.evaluate(cur_x_test, cur_y_test, verbose=0)
pred2 = np.argmax(model.predict(cur_x_test, verbose=0), axis=1)

print(f"3 layers with sigmoid & sigmoid ({test_h2}х{test_w2})")
print("Testing loss:", score[0])
print("Testing accuracy:", score[1])
print("Loss:", h2.history['loss'][-1])
print("Accuracy:", h2.history['sparse_categorical_accuracy'][-1], '\n')

test_h3 = 512
test_w3 = 512

model = tf.keras.Sequential([
    tf.keras.layers.Dense(test_h3, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(test_w3, activation=tf.nn.sigmoid),
    tf.keras.layers.Dense(10)
])
model.compile(loss=loss, metrics=[accuracy], optimizer=optimizer)
h3 = model.fit(dataset, epochs=epochs, batch_size=None, verbose=0)
score = model.evaluate(cur_x_test, cur_y_test, verbose=0)
pred3 = np.argmax(model.predict(cur_x_test, verbose=0), axis=1)

print(f"3 layers with sigmoid & sigmoid ({test_h3}х{test_w3})")
print("Testing loss:", score[0])
print("Testing accuracy:", score[1])
print("Loss:", h3.history['loss'][-1])
print("Accuracy:", h3.history['sparse_categorical_accuracy'][-1], '\n')





3 layers with sigmoid & sigmoid (256х256)
Loss: 0.3576737940311432
Accuracy: 0.8683500289916992
Testing loss: 0.37277960777282715
Testing accuracy: 0.8694000244140625

3 layers with sigmoid & sigmoid (512х256)
Loss: 0.3512374758720398
Accuracy: 0.8713833093643188
Testing loss: 0.3950679302215576
Testing accuracy: 0.8561999797821045

3 layers with sigmoid & sigmoid (512х512)
Loss: 0.3146817982196808
Accuracy: 0.8841333389282227
Testing loss: 0.3521001636981964
Testing accuracy: 0.8733000159263611



## Confusion matrix

In [9]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(cur_y_test, pred1), "\n")
print(confusion_matrix(cur_y_test, pred2), "\n")
print(confusion_matrix(cur_y_test, pred3), "\n")


[[854   0  16  30   3   2  87   0   8   0]
 [  3 951   6  29   6   0   5   0   0   0]
 [ 13   1 782  13 123   0  68   0   0   0]
 [ 35   7   9 895  26   0  25   0   3   0]
 [  0   0  99  41 795   0  64   0   1   0]
 [  0   0   0   1   0 934   0  48   1  16]
 [159   1 102  32  72   0 625   0   9   0]
 [  0   0   0   0   0  25   0 955   0  20]
 [  3   1   7   7   5   3  10   4 960   0]
 [  0   0   0   0   0   8   1  48   0 943]] 

[[862   3  27  30  11   0  53   0  14   0]
 [  3 963   2  22   7   0   1   0   2   0]
 [ 12   1 739  12 211   0  24   0   1   0]
 [ 31  18  12 869  53   1  14   0   2   0]
 [  0   0  66  24 894   0  15   0   1   0]
 [  0   0   0   1   0 941   0  39   4  15]
 [178   1 129  37 212   0 423   0  20   0]
 [  0   0   0   0   0  28   0 956   0  16]
 [  0   1   4   4   8   2   1   3 977   0]
 [  0   0   0   1   0   9   1  51   0 938]] 

[[878   0  16  41   6   2  41   0  16   0]
 [  3 964   2  23   4   0   1   0   3   0]
 [ 17   0 782  13 125   0  56   0   7   0]
 [ 27

Можно сделать вывод, что по результатам проведенного тестирования ширина слоев сети не сильно влияет на точность. 
